version: '3'

services:
  nifi:
    image: "apache/nifi:1.9.2"
    volumes:
      - nifi_data:/opt/nifi/nifi-current/database_repository
      - nifi_flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi_cont:/opt/nifi/nifi-current/content_repository
      - nifi_prov:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_conf:/opt/nifi/nifi-current/conf
      - ${PWD}/nifi/files:/usr/share/files
    restart: always


  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/passwords:/etc/nginx/passwords:ro
    restart: always

volumes:
  nifi_flow:
  nifi_cont:
  nifi_prov:
  nifi_state:
  nifi_conf:
  nifi_data:
